CONTIKI = ../..
# powertrace_src = powertrace.c
energytrace_src = energytrace.c
# ifndef POWERTRACE_TOOLS_MAKEFILE_INCLUDED
# POWERTRACE_TOOLS_MAKEFILE_INCLUDED = 1
# -include $(CONTIKI)/tools/powertrace/Makefile.powertrace
# endif #POWERTRACE_TOOLS_MAKEFILE_INCLUDED